"""create all tables

Revision ID: 8b50a2e1c4f3
Revises: 
Create Date: 2026-03-06 21:51:57.683365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b50a2e1c4f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin_name', sa.String(length=50), nullable=False),
    sa.Column('coin_symbol', sa.String(length=10), nullable=False),
    sa.Column('coin_image', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coin_symbol')
    )
    op.create_table('fear_greed_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fear_greed_index', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fear_greed_index_timestamp'), ['timestamp'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('coin_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin_id', sa.Integer(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('global_volume', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coin_id'], ['coins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coin_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coin_snapshot_timestamp'), ['timestamp'], unique=False)

    op.create_table('historical_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['coin_id'], ['coins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technical_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin_id', sa.Integer(), nullable=False),
    sa.Column('SMA_50', sa.Float(), nullable=False),
    sa.Column('SMA_200', sa.Float(), nullable=False),
    sa.Column('EMA_50', sa.Float(), nullable=False),
    sa.Column('EMA_200', sa.Float(), nullable=False),
    sa.Column('RSI', sa.Float(), nullable=False),
    sa.Column('Stoch_RSI_K', sa.Float(), nullable=True),
    sa.Column('Stoch_RSI_D', sa.Float(), nullable=True),
    sa.Column('MACD', sa.Float(), nullable=False),
    sa.Column('MACD_Signal', sa.Float(), nullable=False),
    sa.Column('Volume_Change', sa.Float(), nullable=False),
    sa.Column('BB_upper', sa.Float(), nullable=True),
    sa.Column('BB_middle', sa.Float(), nullable=True),
    sa.Column('BB_lower', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['coin_id'], ['coins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('top_volume_24h',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin_id', sa.Integer(), nullable=False),
    sa.Column('top_volume', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coin_id'], ['coins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('top_volume_24h', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_top_volume_24h_timestamp'), ['timestamp'], unique=False)

    op.create_table('user_favorite_coins',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('coin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coin_id'], ['coins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'coin_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_favorite_coins')
    with op.batch_alter_table('top_volume_24h', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_top_volume_24h_timestamp'))

    op.drop_table('top_volume_24h')
    op.drop_table('technical_indicators')
    op.drop_table('historical_data')
    with op.batch_alter_table('coin_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coin_snapshot_timestamp'))

    op.drop_table('coin_snapshot')
    op.drop_table('users')
    with op.batch_alter_table('fear_greed_index', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fear_greed_index_timestamp'))

    op.drop_table('fear_greed_index')
    op.drop_table('coins')
    # ### end Alembic commands ###
